spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lumine}
    username: ${DB_USERNAME:lumine}
    password: ${DB_PASSWORD:lumine}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
