export const tokens = {
  background: "#F5F2FF",
  backgroundDeep: "#EDE8FF",
  surface: "#ffffff",
  surfaceMuted: "#F8F5FF",
  primary: "#7B5EA7",
  primaryLight: "#EDE5FF",
  primaryDark: "#523E72",
  primaryContainer: "#D8CCFF",
  accent: "#F4856A",
  safe: "#5BA091",
  danger: "#DC4A4A",
  dangerLight: "#FDECEA",
  secondary: "#7A6B8A",
  secondaryContainer: "#EDE5FF",
  text: "#1A1430",
  textMuted: "#7A6B8A",
  outline: "#E4DCFF",
  tabMuted: "#B0A8C0",
  white: "#ffffff"
} as const;
